apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres
    type: postgres
    access: proxy
    editable: true
    url: postgres:5432
    user: gdev_app
    secureJsonData:
      password: gdev-app-pass
    jsonData:
      database: gdev
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
